version: 0.2

phases:
  install:
    commands:
      - python --version
      - curl -fsSL https://get.pulumi.com > get_pulumi.sh
      - chmod +x get_pulumi.sh
      - ./get_pulumi.sh --version 3.238.0
      - export PATH="$PATH:/root/.pulumi/bin"
      - pulumi version
      - pip install -r requirements.txt

  pre_build:
    commands:
      - chmod +x package.sh
      - ./package.sh

  build:
    commands:
      - pulumi login s3://pulumi-learning-state
      - pulumi stack select dev
      - pulumi config rm aws:profile || true
      - pulumi up -y
